// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: arbtboards-models-instances.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  schemaVersion: 1;
  artboards: 'artboard1' | 'artboard3' | 'artboard2' | 'artboardc1';
  defaultArtboard: 'artboard1';
  stateMachines: {
    artboard1: 'sm13' | 'sm12' | 'sm11';
    artboard3: 'sm33' | 'sm32' | 'sm31';
    artboard2: 'sm23' | 'sm22' | 'sm21';
    artboardc1: 'State Machine 1';
  };
  enums: {};
  viewModels: {
    viewmodel1: {
      _id: 'string';
    };
    viewmodel2: {
      _id: 'string';
    };
    viewmodel3: {
      _id: 'string';
    };
  };
  referencedAssets: {};
}>;
export default asset;
