// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: artboard_db_test.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Main' | 'ArtboardGreen' | 'ArtboardBlue' | 'ArtboardRed';
  defaultArtboard: 'Main';
  stateMachines: {
    Main: 'State Machine 1';
    ArtboardGreen: 'State Machine 1';
    ArtboardBlue: 'State Machine 1';
    ArtboardRed: 'State Machine 1';
  };
  viewModels: {
    MainViewModel: {
      artboard_1: 'artboard';
      artboard_2: 'artboard';
    };
  };
}>;
export default asset;
