// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: blinko.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Main' | 'StoreItem' | 'Token' | 'Indicator' | 'Puck' | 'StoreIcon' | 'Peg' | 'scoreBox';
  defaultArtboard: 'Main';
  stateMachines: {
    Main: 'State Machine 1';
    StoreItem: 'State Machine 1';
    Token: 'State Machine 1';
    Indicator: 'State Machine 1';
    Puck: 'State Machine 1';
    StoreIcon: 'State Machine 1';
    Peg: 'State Machine 1';
    scoreBox: 'State Machine 1';
  };
  viewModels: {
    IndicatorVM: {
      purchased: 'boolean';
    };
    StoreItemVM: {
      tokenCount: 'number';
      height: 'number';
      itemHover: 'boolean';
      cost: 'number';
      description: 'string';
      id: 'string';
      itemType: 'string';
      maxPurchases: 'number';
      name: 'string';
      purchase: 'trigger';
      purchaseCount: 'number';
    };
    storeIconVM: {
      storeiconClick: 'trigger';
      iconHovered: 'boolean';
    };
    storeVM: {
      'xbuttonClick': 'trigger';
      'xbuttonHover': 'boolean';
      'items': 'list';
      'storeOpen': 'boolean';
      'property of pegVM': 'viewModel:pegVM';
      'multiplierValue': 'number';
      'extraTokenSlotActive': 'boolean';
      'extraTokenSlotCost': 'number';
      'extraTokenSlotCount': 'number';
      'purchaseExtraTokenSlot': 'trigger';
      'purchaseSuperMultiplier': 'trigger';
      'superMultiplierActive': 'boolean';
      'superMultiplierCost': 'number';
      'superMultiplierCount': 'number';
    };
    TokenVM: {
      spinToken: 'boolean';
    };
    pegVM: {
      blink: 'trigger';
      multiplierValue: 'number';
      pegType: 'enum:normal|multiplier';
      pegBounced: 'trigger';
    };
    gameLogicVM: {
      turnTokens: 'number';
      turnScore: 'number';
      buttonLabel: 'string';
      message: 'string';
      startTurn: 'trigger';
      turnEnded: 'trigger';
      gameEnded: 'boolean';
      tokenCount: 'number';
      scoreTotal: 'number';
    };
    scoreBox: {
      Token: 'viewModel:TokenVM';
      slotType: 'enum:addToken|normal';
      landed: 'trigger';
      scoreValue: 'number';
    };
    PuckVM: {
      puckBounce: 'trigger';
      puckRotation: 'number';
    };
    main: {
      'PuckVM': 'viewModel:PuckVM';
      'storeItemVM': 'viewModel:StoreItemVM';
      'storeIconVM': 'viewModel:storeIconVM';
      'pegVM': 'viewModel:pegVM';
      'storeVM': 'viewModel:storeVM';
      'buttonHover': 'boolean';
      'tokenVM': 'viewModel:TokenVM';
      'property of gameLogicVM': 'viewModel:gameLogicVM';
    };
  };
  assets: {};
}>;
export default asset;
