// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: databinding.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  schemaVersion: 1;
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  enums: {
    Pets: 'chipmunk' | 'rat' | 'frog' | 'owl' | 'cat' | 'dog';
  };
  viewModels: {
    Person: {
      pet: 'viewModel:Pet';
      jump: 'trigger';
      likes_popcorn: 'boolean';
      favourite_pet: 'enum:Pets';
      favourite_color: 'color';
      age: 'number';
      website: 'string';
      name: 'string';
    };
    Pet: {
      type: 'enum:Pets';
      name: 'string';
    };
  };
  referencedAssets: {};
}>;
export default asset;
