// Generated by rive-gen-types — do not edit manually. @generated
// eslint-disable
// Source: databinding.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  viewModels: {
    Person: {
      pet: 'viewModel:Pet';
      jump: 'trigger';
      likes_popcorn: 'boolean';
      favourite_pet: 'enum:chipmunk|rat|frog|owl|cat|dog';
      favourite_color: 'color';
      age: 'number';
      website: 'string';
      name: 'string';
    };
    Pet: {
      type: 'enum:chipmunk|rat|frog|owl|cat|dog';
      name: 'string';
    };
  };
}>;
export default asset;
