// Generated by rive-gen-types — do not edit manually. @generated
// eslint-disable
// Source: databinding_images.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    'Artboard': 'State Machine 1';
  };
  viewModels: {
    'MyViewModel': {
      'bound_image': 'image';
    };
  };
}>;
export default asset;
