// Generated by rive-gen-types — do not edit manually. @generated
// eslint-disable
// Source: databinding_lists.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    'Artboard': 'State Machine 1';
  };
  viewModels: {
    'Person': {
      'name': 'string';
    };
    'DevRel': {
      'team': 'list';
    };
  };
}>;
export default asset;
