// Generated by rive-gen-types — do not edit manually. @generated
// eslint-disable
// Source: databinding.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    'Artboard': 'State Machine 1';
  };
  viewModels: {
    'Person': {
      'pet': 'viewModel:Pet';
      'jump': 'trigger';
      'likes_popcorn': 'boolean';
      'favourite_pet': 'enumType';
      'favourite_color': 'color';
      'age': 'number';
      'website': 'string';
      'name': 'string';
    };
    'Pet': {
      'type': 'enumType';
      'name': 'string';
    };
  };
}>;
export default asset;
