// Generated by rive-gen-types — do not edit manually. @generated
// eslint-disable
// Source: fallback_fonts.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    'Artboard': 'State Machine 1';
  };
}>;
export default asset;
