// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: finished_trigger.riv
import type { RiveFileSource } from '@rive-app/react-native';
declare const asset: RiveFileSource<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  enums: {};
  viewModels: {
    ViewModel1: {
      finished: 'trigger';
    };
  };
  referencedAssets: {};
}>;
export default asset;
