// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: font_fallback.riv
import type { RiveFileSource } from '@rive-app/react-native';
declare const asset: RiveFileSource<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  enums: {};
  viewModels: {
    ViewModel: {
      text: 'string';
    };
  };
  referencedAssets: {};
}>;
export default asset;
