// Generated by rive-gen-types — do not edit manually. @generated
// eslint-disable
// Source: font_fallback.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  viewModels: {
    ViewModel: {
      text: 'string';
    };
  };
}>;
export default asset;
