// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: hello_world_text.riv
import type { RiveFileSource } from '@rive-app/react-native';
declare const asset: RiveFileSource<{
  schemaVersion: 1;
  artboards: 'New Artboard';
  defaultArtboard: 'New Artboard';
  stateMachines: {
    'New Artboard': 'State Machine 1';
  };
  enums: {};
  viewModels: {};
  referencedAssets: {};
}>;
export default asset;
