// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: inputglow.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Layout';
  defaultArtboard: 'Layout';
  stateMachines: {
    Layout: 'State';
  };
  viewModels: {
    ViewModel: {
      isFocused: 'boolean';
    };
  };
  assets: {};
}>;
export default asset;
