// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: layouts_demo.riv
import type { RiveFileSource } from '@rive-app/react-native';
declare const asset: RiveFileSource<{
  schemaVersion: 1;
  artboards: 'iOS_Android_Layouts_demo_v01';
  defaultArtboard: 'iOS_Android_Layouts_demo_v01';
  stateMachines: {
    iOS_Android_Layouts_demo_v01: 'State Machine 1';
  };
  enums: {};
  viewModels: {};
  referencedAssets: {};
}>;
export default asset;
