// Generated by rive-gen-types — do not edit manually. @generated
// eslint-disable
// Source: many_viewmodels.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  viewModels: {
    First: {
      imageValue: 'image';
      colorValue: 'color';
      textValue: 'string';
    };
  };
}>;
export default asset;
