// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: many_viewmodels.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  schemaVersion: 1;
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  enums: {};
  viewModels: {
    First: {
      imageValue: 'assetImage';
      colorValue: 'color';
      textValue: 'string';
    };
  };
  referencedAssets: {};
}>;
export default asset;
