// Generated by rive-gen-types — do not edit manually. @generated
// eslint-disable
// Source: on_entry_test.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    'Artboard': 'State Machine 1';
  };
  viewModels: {
    'vm': {
      'input': 'number';
      'inputOnEntry': 'number';
    };
  };
}>;
export default asset;
