// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: on_entry_test.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  schemaVersion: 1;
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  enums: {};
  viewModels: {
    vm: {
      input: 'number';
      inputOnEntry: 'number';
    };
  };
  referencedAssets: {
    'Inter-4228759': 'font';
  };
}>;
export default asset;
