// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: out_of_band.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  viewModels: {};
}>;
export default asset;
