// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: out_of_band.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  viewModels: {};
  assets: {
    'Inter-594377': 'font';
    'referenced-image-2929282': 'image';
    'referenced_audio-2929340': 'audio';
    'hosted_audio-2989208': 'audio';
    'Damion-593587': 'font';
    'cdn-image-2989123': 'image';
  };
}>;
export default asset;
