// Generated by rive-gen-types — do not edit manually. @generated
// eslint-disable
// Source: quick_start.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'health_bar_v01';
  defaultArtboard: 'health_bar_v01';
  stateMachines: {
    health_bar_v01: 'State Machine 1';
  };
  viewModels: {
    health_bar_01: {
      gameOver: 'trigger';
      hoverYes: 'boolean';
      hoverNo: 'boolean';
      healthColor: 'color';
      health: 'number';
    };
  };
}>;
export default asset;
