// Generated by rive-gen-types — do not edit manually. @generated
// eslint-disable
// Source: rating.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'New Artboard';
  defaultArtboard: 'New Artboard';
  stateMachines: {
    'New Artboard': 'State Machine 1';
  };
}>;
export default asset;
