// Generated by rive-gen-types — do not edit manually. @generated
// eslint-disable
// Source: rewards.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards:
    | 'Main'
    | 'Lives 2'
    | 'Item Value'
    | 'Chest'
    | 'Button'
    | 'Heart'
    | 'Item';
  defaultArtboard: 'Main';
  stateMachines: {
    'Main': 'State Machine 1';
    'Lives 2': 'State Machine 1';
    'Item Value': 'State Machine 1';
    'Chest': 'State Machine 1';
    'Button': 'State Machine 1';
    'Heart': 'State Machine 1';
    'Item': 'State Machine 1';
  };
  viewModels: {
    Item_Icon_Value: {
      Icon_React: 'trigger';
      Property_Of_Item: 'viewModel:Item';
      Item_Value: 'number';
    };
    Energy_Bar: {
      Bar_Color: 'color';
      Lives: 'number';
      Energy_Bar: 'number';
    };
    Rewards: {
      Price_Value: 'number';
      Color: 'color';
      Height: 'number';
      With: 'number';
      Item_Selection: 'viewModel:Item';
      Item_Value_Icon: 'viewModel:Item_Icon_Value';
      Button: 'viewModel:Button';
      Coin: 'viewModel:Item_Icon_Value';
      Gem: 'viewModel:Item_Icon_Value';
      Energy_Bar: 'viewModel:Energy_Bar';
    };
    Button: {
      State_1: 'string';
      Item_Text: 'string';
      Item: 'viewModel:Item';
      Pressed: 'trigger';
    };
    Item: {
      Item_Selection: 'enumType';
    };
  };
}>;
export default asset;
