// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: script_binding_probe.riv
import type { RiveFileSource } from '@rive-app/react-native';
declare const asset: RiveFileSource<{
  schemaVersion: 1;
  artboards: 'Binding Probe' | 'NuRiveWordmark01' | 'NuRiveBrandmark01' | 'Watermark';
  defaultArtboard: 'Binding Probe';
  stateMachines: {
    'Binding Probe': 'Main';
    'NuRiveWordmark01': 'State Machine 1';
    'NuRiveBrandmark01': 'State Machine 1';
    'Watermark': 'State Machine 1';
  };
  enums: {};
  viewModels: {
    ProbeModel: {
      seed: 'number';
      observedSeed: 'number';
      isReady: 'number';
    };
    RiveCLIBootUp: {

    };
  };
  referencedAssets: {};
}>;
export default asset;
