// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: settle_probe.riv
import type { RiveFileSource } from '@rive-app/react-native';
declare const asset: RiveFileSource<{
  schemaVersion: 1;
  artboards: 'Probe' | 'Ticker';
  defaultArtboard: 'Probe';
  stateMachines: {
    Probe: 'State Machine 1';
    Ticker: 'State Machine 1';
  };
  enums: {};
  viewModels: {
    Probe: {
      input: 'number';
      output: 'number';
    };
    Ticker: {
      phase: 'number';
    };
  };
  referencedAssets: {};
}>;
export default asset;
