// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: tabtest.riv
import type { RiveFileSource } from '@rive-app/react-native';
declare const asset: RiveFileSource<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  enums: {
    Selected: 'All' | 'Parent' | 'Child';
  };
  viewModels: {
    ViewModel1: {
      enumProperty: 'enum:Selected';
    };
  };
  referencedAssets: {};
}>;
export default asset;
