// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: viewmodelproperty.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  enums: {};
  viewModels: {
    root: {
      vm2: 'viewModel:vm';
      vm1: 'viewModel:vm';
    };
    vm: {
      name: 'string';
    };
  };
  referencedAssets: {};
}>;
export default asset;
