// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: vm_value_change_test.riv
import type { RiveFileSource } from '@rive-app/react-native';
declare const asset: RiveFileSource<{
  schemaVersion: 1;
  artboards: 'Artboard';
  defaultArtboard: 'Artboard';
  stateMachines: {
    Artboard: 'State Machine 1';
  };
  enums: {};
  viewModels: {
    TextModel: {
      trigger: 'trigger';
      textValue: 'string';
    };
  };
  referencedAssets: {};
}>;
export default asset;
