// Generated by rive-gen-types — do not edit manually. @generated
/* eslint-disable */
// Source: riv-schema.riv
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
  artboards: 'Main' | 'O\'Brien\'s Board';
  defaultArtboard: 'Main';
  stateMachines: {
    'Main': 'State Machine 1' | 'Hover|Press';
    'O\'Brien\'s Board': 'It\'s SM';
  };
  enums: {
    Status: 'idle' | 'running' | 'failed';
    Weird: 'a|b' | 'it\'s';
  };
  viewModels: {
    Card: {
      title: 'string';
      count: 'number';
      done: 'boolean';
      tint: 'color';
      tap: 'trigger';
      status: 'enum:Status';
    };
    Screen: {
      'card': 'viewModel:Card';
      'mode': 'enum:Status';
      'weird': 'enum:Weird';
      'page title': 'string';
      'blend': 'enum';
    };
  };
  referencedAssets: {
    'ref_image-1': 'image';
    'hosted_image-2': 'image';
    'beep-3': 'audio';
  };
}>;
export default asset;
