import type { RiveFile } from '../specs/RiveFile.nitro';

/**
 * Describes the statically-known shape of a .riv file.
 * Extend this interface via generated schema files to get type-safe artboard names.
 *
 * @example Generated by: yarn rive-gen-types path/to/file.riv
 * ```ts
 * export type MySchema = RiveFileSchema & {
 *   artboards: 'Main' | 'Intro' | 'GameOver';
 * };
 * ```
 */
export interface RiveFileSchema {
  artboards: string;
  defaultArtboard: string;
  stateMachines: Record<string, string>;
  viewModels: Record<string, Record<string, string>>;
}

/**
 * A Metro asset (number) branded with a schema type `T`.
 * The `__riveSchema` field is purely phantom — it never exists at runtime.
 *
 * Created automatically when you `import asset from './file.riv'` and a
 * corresponding `file.riv.d.ts` has been generated by `yarn rive-gen-types`.
 *
 * Pass to `RiveFileFactory.fromSource(asset)` — TypeScript infers `T` automatically.
 */
export type RiveAsset<T extends RiveFileSchema = RiveFileSchema> = number & {
  readonly __riveSchema?: T;
};

/**
 * A RiveFile branded with a schema type `T`.
 * The `__schema` field is purely a phantom type — it never exists at runtime.
 *
 * Obtain one via `RiveFileFactory.fromURL<MySchema>(...)` or
 * `RiveFileFactory.fromSource(typedAsset)`.
 */
export type TypedRiveFile<T extends RiveFileSchema = RiveFileSchema> =
  RiveFile & {
    readonly __schema?: T;
  };
