import type { RiveFile } from '../specs/RiveFile.nitro';

/**
 * Describes the statically-known shape of a .riv file.
 * Extend this interface via generated schema files to get type-safe artboard names.
 *
 * @example Generated by: yarn rive-gen-types path/to/file.riv
 * ```ts
 * export type MySchema = RiveFileSchema & {
 *   artboards: 'Main' | 'Intro' | 'GameOver';
 * };
 * ```
 */
export interface RiveFileSchema {
  artboards: string;
  defaultArtboard: string;
  stateMachines: Record<string, string>;
  viewModels: Record<string, Record<string, string>>;
  /**
   * Non-embedded (referenced or CDN) assets that the app must supply via
   * `referencedAssets`: unique asset identifier (e.g. 'Inter-594377') →
   * 'image' | 'font' | 'audio'.
   */
  assets: Record<string, string>;
}

/**
 * A Metro asset (number) branded with a schema type `T`.
 * The `__riveSchema` field is purely phantom — it never exists at runtime.
 *
 * Created automatically when you `import asset from './file.riv'` and a
 * corresponding `file.riv.d.ts` has been generated by `yarn rive-gen-types`.
 *
 * Pass to `RiveFileFactory.fromSource(asset)` — TypeScript infers `T` automatically.
 */
export type RiveAsset<T extends RiveFileSchema = RiveFileSchema> = number & {
  readonly __riveSchema?: T;
};

/**
 * Extracts the RiveFileSchema from a RiveAsset, TypedRiveFile, or a bare RiveFileSchema.
 *
 * @example
 * import rewardsRiv from './rewards.riv';
 * type Schema = SchemaOf<typeof rewardsRiv>; // RewardsSchema
 */
export type SchemaOf<T> = T extends {
  readonly __riveSchema?: infer S extends RiveFileSchema;
}
  ? S
  : T extends { readonly __schema?: infer S extends RiveFileSchema }
    ? S
    : T extends RiveFileSchema
      ? T
      : never;

/**
 * A RiveFile branded with a schema type `T`.
 * The `__schema` field is purely a phantom type — it never exists at runtime.
 *
 * Accepts either a `RiveFileSchema` or a `RiveAsset<T>` (i.e. `typeof myRiv`).
 *
 * Obtain one via `RiveFileFactory.fromURL<MySchema>(...)` or
 * `RiveFileFactory.fromSource(typedAsset)`.
 */
export type TypedRiveFile<
  T extends RiveFileSchema | RiveAsset = RiveFileSchema,
> = RiveFile & {
  readonly __schema?: SchemaOf<T>;
};
