import type { RiveFile } from '../specs/RiveFile.nitro';

/**
 * Describes the statically-known shape of a .riv file. Generated schemas
 * (`yarn rive-gen-types path/to/file.riv`) are plain object types that
 * satisfy it structurally.
 *
 * Don't write a schema as `RiveFileSchema & { … }`: the base's index
 * signatures make every artboard, view model and enum name valid.
 */
export interface RiveFileSchema {
  /**
   * Format version of generated schemas. Bumped on every breaking format
   * change, so a `.riv.d.ts` from an older generator is reported as out of
   * date instead of silently checking the wrong thing.
   */
  schemaVersion: 1;
  artboards: string;
  defaultArtboard: string;
  stateMachines: Record<string, string>;
  /** File-level enum definitions, name → value union. */
  enums: Record<string, string>;
  viewModels: Record<string, Record<string, string>>;
  /**
   * Non-embedded (referenced or hosted) assets that the app must supply via
   * the `referencedAssets` option: the asset's runtime `uniqueName`
   * (e.g. 'Inter-594377') → 'image' | 'font' | 'audio'.
   */
  referencedAssets: Record<string, string>;
}

/**
 * A `.riv` import (a Metro asset number) branded with a schema type `T`.
 * The `__riveSchema` field is purely phantom — it never exists at runtime.
 *
 * Created automatically when you `import asset from './file.riv'` and a
 * corresponding `file.riv.d.ts` has been generated by `yarn rive-gen-types`.
 *
 * Pass to `RiveFileFactory.fromSource(asset)` — TypeScript infers `T` automatically.
 */
// An outdated schema resolves to an object keyed by the fix, so the message
// shows up in the compiler error at the use site; `skipLibCheck` hides the
// schema's own mismatch inside the `.d.ts`.
export type RiveFileSource<T = RiveFileSchema> = [T] extends [RiveFileSchema]
  ? SchemaBranded<T>
  : {
      readonly 'This .riv.d.ts is out of date: regenerate it with npx rive-gen-types': true;
    };

/** A Metro asset number carrying schema `T` as a phantom property. */
export type SchemaBranded<T> = number & { readonly __riveSchema?: T };

/**
 * Extracts the RiveFileSchema from a RiveFileSource, TypedRiveFile, or a bare RiveFileSchema.
 *
 * @example
 * import rewardsRiv from './rewards.riv';
 * type Schema = SchemaOf<typeof rewardsRiv>; // RewardsSchema
 */
export type SchemaOf<T> = T extends {
  readonly __riveSchema?: infer S extends RiveFileSchema;
}
  ? S
  : T extends { readonly __schema?: infer S extends RiveFileSchema }
    ? S
    : T extends RiveFileSchema
      ? T
      : never;

/**
 * A RiveFile branded with a schema type `T`.
 * The `__schema` field is purely a phantom type — it never exists at runtime.
 *
 * Accepts either a `RiveFileSchema` or a `RiveFileSource<T>` (i.e. `typeof myRiv`).
 *
 * Obtain one via `RiveFileFactory.fromURL<MySchema>(...)` or
 * `RiveFileFactory.fromSource(typedAsset)`.
 */
export type TypedRiveFile<
  T extends RiveFileSchema | RiveFileSource = RiveFileSchema,
> = RiveFile & {
  readonly __schema?: SchemaOf<T>;
};
