#!/usr/bin/env bun
/**
 * Generates .riv.d.ts declaration files so that `import asset from './file.riv'`
 * is automatically typed in TypeScript without any extra imports.
 *
 * Usage:
 *   bun scripts/rive-gen-types.ts <path-or-url>          # writes <file>.riv.d.ts next to the source
 *   bun scripts/rive-gen-types.ts <path> --out <out.ts>  # write a standalone schema .ts instead
 *   bun scripts/rive-gen-types.ts --all <directory>      # generate for every .riv in a directory
 *
 * After generation, TypeScript resolves the .riv.d.ts automatically:
 *   import gameRiv from './assets/game.riv';              // typed as RiveAsset<GameSchema>
 *   const file = await RiveFileFactory.fromSource(gameRiv); // TypedRiveFile<GameSchema> — T inferred
 */

import { spawnSync } from 'child_process';
import { writeFileSync, mkdirSync, readdirSync, statSync } from 'fs';
import { dirname, resolve, basename, extname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const extractorPath = resolve(__dirname, 'rive-extract-schema.ts');

interface Schema {
  artboards: string[];
  defaultArtboard: string;
  stateMachines: Record<string, string[]>;
  viewModels: Record<string, Record<string, string>>;
}

function extractSchema(input: string): Schema {
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const result = spawnSync('bun', [extractorPath, input], {
        encoding: 'utf8',
        timeout: 30_000,
      });
      if (result.error) throw result.error;
      if (result.signal) throw new Error(`bun killed by signal ${result.signal}\n${result.stderr}`);
      if (result.status !== 0)
        throw new Error(
          result.stderr || `bun exited with code ${result.status}`
        );
      if (!result.stdout.trim())
        throw new Error(
          `bun exited 0 but produced no output\nstderr: ${result.stderr || '(empty)'}`
        );
      return JSON.parse(result.stdout) as Schema;
    } catch (err) {
      if (attempt === 1) throw err;
    }
  }
  throw new Error('unreachable');
}

// With prettier quoteProps:"consistent", if any key in an object needs quotes, all get quotes.
const IDENTIFIER_RE = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;
const needsQuote = (s: string) => !IDENTIFIER_RE.test(s);
const quoteKey = (s: string, forceQuote: boolean) =>
  forceQuote || needsQuote(s) ? `'${s}'` : s;

function smRecord(stateMachines: Record<string, string[]>): string {
  const keys = Object.keys(stateMachines);
  const force = keys.some(needsQuote);
  return Object.entries(stateMachines)
    .map(([ab, sms]) => {
      const union = sms.length ? sms.map((s) => `'${s}'`).join(' | ') : 'never';
      return `    ${quoteKey(ab, force)}: ${union};`;
    })
    .join('\n');
}

function vmRecord(viewModels: Record<string, Record<string, string>>): string {
  const vmKeys = Object.keys(viewModels);
  const forceVmKeys = vmKeys.some(needsQuote);
  return Object.entries(viewModels)
    .map(([vmName, props]) => {
      const propKeys = Object.keys(props);
      const forcePropKeys = propKeys.some(needsQuote);
      const propLines = Object.entries(props)
        .map(
          ([propName, propType]) =>
            `      ${quoteKey(propName, forcePropKeys)}: '${propType}';`
        )
        .join('\n');
      return `    ${quoteKey(vmName, forceVmKeys)}: {\n${propLines}\n    };`;
    })
    .join('\n');
}

function schemaBody(schema: Schema): string {
  const vmSection =
    Object.keys(schema.viewModels).length > 0
      ? `\n  viewModels: {\n${vmRecord(schema.viewModels)}\n  };`
      : '';
  return `\
  artboards: ${schema.artboards.map((a) => `'${a}'`).join(' | ')};
  defaultArtboard: '${schema.defaultArtboard}';
  stateMachines: {
${smRecord(schema.stateMachines)}
  };${vmSection}`;
}

function dtsContent(input: string, schema: Schema): string {
  return `\
// Generated by rive-gen-types — do not edit manually. @generated
// eslint-disable
// Source: ${basename(input)}
import type { RiveAsset } from '@rive-app/react-native';
declare const asset: RiveAsset<{
${schemaBody(schema)}
}>;
export default asset;
`;
}

function standaloneContent(
  input: string,
  typeName: string,
  schema: Schema
): string {
  return `\
// Generated by rive-gen-types — do not edit manually.
// Source: ${input}
import type { RiveFileSchema } from '@rive-app/react-native';

export type ${typeName} = RiveFileSchema & {
${schemaBody(schema)}
};
`;
}

function generate(
  input: string,
  outPath: string,
  mode: 'dts' | 'standalone',
  typeName?: string
) {
  let schema: Schema;
  try {
    schema = extractSchema(input);
  } catch (err) {
    process.stderr.write(
      `Failed to extract schema from ${input}: ${err instanceof Error ? err.message : String(err)}\n`
    );
    process.exit(1);
  }

  if (!schema.artboards?.length) {
    process.stderr.write(`No artboards found in ${input}.\n`);
    process.exit(1);
  }

  const content =
    mode === 'dts'
      ? dtsContent(input, schema)
      : standaloneContent(input, typeName!, schema);

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, content, 'utf8');
  process.stdout.write(`Written: ${outPath}\n`);
}

function findRivFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = resolve(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...findRivFiles(full));
    } else if (extname(entry) === '.riv') {
      results.push(full);
    }
  }
  return results;
}

// --- CLI ---

// noUncheckedIndexedAccess: slice gives string[], index access gives string | undefined
const args: string[] = process.argv.slice(2);

if (args[0] === '--all') {
  const dir: string | undefined = args[1];
  if (!dir) {
    process.stderr.write('Usage: rive-gen-types --all <directory>\n');
    process.exit(1);
  }
  const files = findRivFiles(resolve(process.cwd(), dir));
  if (!files.length) {
    process.stderr.write(`No .riv files found in ${dir}\n`);
    process.exit(1);
  }
  for (const file of files) {
    generate(file, `${file}.d.ts`, 'dts');
  }
  process.exit(0);
}

if (!args.length || args[0]!.startsWith('--')) {
  process.stderr.write(
    'Usage:\n' +
      '  rive-gen-types <path-or-url>               # writes <file>.riv.d.ts\n' +
      '  rive-gen-types <path> --out <out.ts>        # standalone schema .ts\n' +
      '  rive-gen-types --all <directory>            # all .riv files in dir\n'
  );
  process.exit(1);
}

const input = args[0]!;
const outIdx = args.indexOf('--out');

if (outIdx !== -1) {
  // Standalone mode: generate a named schema type, not a .d.ts
  const outPath = resolve(process.cwd(), args[outIdx + 1]!);
  const baseName = basename(input, '.riv').replace(/[^a-zA-Z0-9]/g, '_');
  const nameIdx = args.indexOf('--name');
  const typeName =
    nameIdx !== -1
      ? args[nameIdx + 1]!
      : baseName.charAt(0).toUpperCase() + baseName.slice(1) + 'Schema';
  generate(input, outPath, 'standalone', typeName);
} else {
  if (input.startsWith('http://') || input.startsWith('https://')) {
    process.stderr.write(
      `Error: URL inputs require --out to specify the output path.\n` +
        `  Example: rive-gen-types ${input} --out ./assets/file.riv.d.ts\n`
    );
    process.exit(1);
  }
  // Default: write <file>.riv.d.ts next to the source file
  const absInput = resolve(process.cwd(), input);
  generate(input, `${absInput}.d.ts`, 'dts');
}
